---
- hosts: all
  become: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "azavea.ntp" }
    - { role: "azavea.terraform" }
    - { role: "azavea.docker" }
    - { role: "raster-vision.environment" }
    - { role: "raster-vision.awscli" }
    - { role: "raster-vision.nvidia-docker" }
    - { role: "raster-vision.compose-docker" }
